## .NET ##
# User-specific files
*.user
*.userosscache
*.suo
*.userprefs

# User-specific folders
.idea/

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Dd]ist/
[Dd]ebug-*/ 
[Dd]ebug/**/
[Dd]Release/
[Dd]ReleasePublic/
[Dd]Release-*/ 
[Dd]Release/**/

# Windows Installer files
*.cab
*.msi
*.msm
*.msp

# Windows Installer XML files
*.wixproj

# ASP.NET Scaffolding
ScaffoldingReadMe.txt

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/

# ASP.NET vNext
project.json

## ASP.NET ##
# Ignore build output directories
bin/
obj/

# Ignore files generated by Visual Studio for Mac
.vscode/

# User-specific files
.vs/

# Windows Installer files
*.cab
*.msi
*.msm
*.msp

# JetBrains Rider
.idea/

# User-specific configuration files
.vscode/

# ASP.NET core and VS
.vs2019/
.vs2017/
.vs2015/
